// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhw-Ir8lDekhrUEsLqHGlnN0Dy0Ywaz4',
    appId: '1:817777852918:web:ae248eaca785f05e4047d7',
    messagingSenderId: '817777852918',
    projectId: 'vipralap',
    authDomain: 'vipralap.firebaseapp.com',
    storageBucket: 'vipralap.firebasestorage.app',
    measurementId: 'G-91YHG2D70J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYP_9IVLeQ28v3nAWKzSt3tIRZKHembBE',
    appId: '1:817777852918:android:4e4cd056f85d21564047d7',
    messagingSenderId: '817777852918',
    projectId: 'vipralap',
    storageBucket: 'vipralap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpl7tm31VSY3bvaPtF4teqTiSljDzEWVo',
    appId: '1:817777852918:ios:f760bd6dd0a0ec564047d7',
    messagingSenderId: '817777852918',
    projectId: 'vipralap',
    storageBucket: 'vipralap.firebasestorage.app',
    iosBundleId: 'com.example.vipraLap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpl7tm31VSY3bvaPtF4teqTiSljDzEWVo',
    appId: '1:817777852918:ios:f760bd6dd0a0ec564047d7',
    messagingSenderId: '817777852918',
    projectId: 'vipralap',
    storageBucket: 'vipralap.firebasestorage.app',
    iosBundleId: 'com.example.vipraLap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUhw-Ir8lDekhrUEsLqHGlnN0Dy0Ywaz4',
    appId: '1:817777852918:web:0b3c29bb6cc9f6174047d7',
    messagingSenderId: '817777852918',
    projectId: 'vipralap',
    authDomain: 'vipralap.firebaseapp.com',
    storageBucket: 'vipralap.firebasestorage.app',
    measurementId: 'G-4TG1QBQ67L',
  );

}